2023-05-11 08:03:35.735 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPConnectionPool(host='192.168.0.112', port=8086): Max retries exceeded with url: /write?db=home_assistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f1c3e23b0>: Failed to establish a new connection: [Errno 111] Connection refused'))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2023-05-11 08:03:38.554 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Pendrive Mi TV' for androidtv_remote integration not ready yet: Couldn't connect to 192.168.0.104:6466; Retrying in background
2023-05-11 08:04:35.792 ERROR (SyncWorker_6) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"code":"unauthorized","message":"Unauthorized"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.
2023-05-11 08:05:35.797 ERROR (SyncWorker_2) [homeassistant.components.influxdb] InfluxDB database is not accessible due to '401: {"code":"unauthorized","message":"Unauthorized"}'. Please check that the database, username and password are correct and that the specified user has the correct permissions set. Retrying in 60 seconds.
