2023-05-11 19:51:51.809 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPConnectionPool(host='192.168.0.112', port=8086): Max retries exceeded with url: /write?db=home_assistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f75ec98d0f0>: Failed to establish a new connection: [Errno 111] Connection refused'))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2023-05-11 19:51:54.627 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Pendrive Mi TV' for androidtv_remote integration not ready yet: Couldn't connect to 192.168.0.104:6466; Retrying in background
